# Generated by Django 4.2 on 2023-04-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient", old_name="name", new_name="fullname",
        ),
        migrations.AddField(
            model_name="patient",
            name="username",
            field=models.CharField(default="Empty", max_length=100),
            preserve_default=False,
        ),
    ]
