# Generated by Django 4.2 on 2023-04-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointment", "0002_rename_name_patient_fullname_patient_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor", old_name="name", new_name="fullname",
        ),
        migrations.AddField(
            model_name="doctor",
            name="username",
            field=models.CharField(default="Empty", max_length=100),
            preserve_default=False,
        ),
    ]
